[workspace]

members = [
    "core",
    "frontends/desktop-native",
    "frontends/wasm",
]

[profile.dev]
overflow-checks = false

[profile.release]
#lto = true
opt-level = 3

[profile.release-lto]
inherits = "release"
lto = true
codegen-units = 1

[profile.release-lto.package."*"]
opt-level = 3