[package]
name = "gba-rust-backend-only"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gba-core = {path = "../../core"}
clap = { version = "3.1.18", features = ["derive"] }
