mod algorithm;
mod apu;
mod bus;
mod config;
mod cpu;
mod dma_channel;
mod gba;
mod input_handler;
mod ppu;
mod timer;
mod util;
mod cp15;
mod spi;

pub use apu::SoundBufferIt;
pub use config::NUM_SAVE_STATES;
pub use config::SAVE_STATE_SIZE;
pub use gba::GBA;
pub use input_handler::KeyInput;
pub use ppu::{Pixel, ScreenBuffer};
pub use util::marshall_save_state;
